services:

  pymupdf:
    build:
      context: .
      dockerfile: docker/pymupdf/Dockerfile

    volumes:
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./data/raw:/data/raw:ro
      - ./outputs:/outputs
      - ./metrics:/metrics

    working_dir: /app

    entrypoint:
      - python
      - /app/src/parsers/pymupdf_baseline.py


  docling:
    build:
      context: .
      dockerfile: docker/docling/Dockerfile

    environment:
      DOCLING_INFERENCE_COMPILE_TORCH_MODELS: "false"
      TRANSFORMERS_VERBOSITY: "error"
      HF_HUB_DISABLE_PROGRESS_BARS: "1"
      TOKENIZERS_PARALLELISM: "false"

    volumes:
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./data/raw:/data/raw:ro
      - ./outputs:/outputs
      - ./metrics:/metrics
      - ./models/docling:/home/appuser/.cache

    working_dir: /app

    entrypoint:
      - python
      - /app/src/parsers/docling_baseline.py
