services:

  pymupdf:
    build:
      context: .
      dockerfile: docker/pymupdf/Dockerfile

    volumes:
      - ./config:/app/config:ro
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./data:/data:ro
      - ./outputs:/outputs
      - ./metrics:/metrics

    working_dir: /app

    entrypoint:
      - python
      - /app/src/parsers/pymupdf_baseline.py


  docling:
    build:
      context: .
      dockerfile: docker/docling/Dockerfile

    environment:
      DOCLING_INFERENCE_COMPILE_TORCH_MODELS: "false"
      TRANSFORMERS_VERBOSITY: "error"
      HF_HUB_DISABLE_PROGRESS_BARS: "1"
      TOKENIZERS_PARALLELISM: "false"

    volumes:
      - ./config:/app/config:ro
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./data:/data:ro
      - ./outputs:/outputs
      - ./metrics:/metrics
      - ./models/docling:/home/appuser/.cache

    working_dir: /app

    entrypoint:
      - python
      - /app/src/parsers/docling_baseline.py

  mineru:
    build:
      context: .
      dockerfile: docker/mineru/Dockerfile

    environment:
      MINERU_MODEL_SOURCE: local
      MINERU_TOOLS_CONFIG_JSON: /models/mineru/mineru.json
      HF_HOME: /models/mineru/huggingface
      HF_HUB_DISABLE_PROGRESS_BARS: "1"
      TOKENIZERS_PARALLELISM: "false"

    volumes:
      - ./config:/app/config:ro
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./data:/data:ro
      - ./outputs:/outputs
      - ./metrics:/metrics
      - ./models/mineru:/models/mineru

    working_dir: /app

    entrypoint:
      - python
      - /app/src/parsers/mineru_baseline.py

  paddleocr:
    build:
      context: .
      dockerfile: docker/paddleocr/Dockerfile

    environment:
      HOME: /home/appuser

    volumes:
      - ./config:/app/config:ro
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./data:/data:ro
      - ./outputs:/outputs
      - ./metrics:/metrics
      - ./models/paddleocr:/home/appuser/.paddlex

    working_dir: /app

    entrypoint:
      - python
      - /app/src/parsers/paddleocr_v2.py
